language: node_js
cache: yarn
node_js:
- '11'
script:
- npm i bs-platform --no-save
- yarn build
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: YGeaxwJ7UyMxReyQTGCpi3TDB47QFAh7zFU1YSa7SvmuEpAh70HGQCMzzc1oFa7vUc+tKjBwcBc7LzpQxhDXnVxLtj5kMLlhlGReNt8zceMiy++K/iZVTOBzM8H1UtL77Ip+HHtAJkUdxi9rVJHlsITSYVPoU/lIIGPzfhcfjK2nfoBxvk2iXqObq094pI9WHHnsG90MMH6cw6HcbcVhQCvA0ZbP5wQR6Tk6eiuSCLma5jYb8slpo0VF1U8UYrOOpdUtZjPb35hTJfN10Ua0Y/y0kFDK8XCEsCSJlDGT0spl6wFy47qZBVYKkR10Qx8in0gpDOmMZ/SCBWq55tbhfOnJmbujLV0XPx/dD83T662GUPyxCPztl7BnnsuGhJl9itWjcnk0FERoqUOYSayU9Gsq5bAEl63nlF/qJnUESWCrdaZMc0XcB7naShANdNCAeNLbz4yfm2JY4LAySGxD6EA7yKjcQSridgHyfVcvKSyfyPck/7cQ9mxCafrv6xRMRJ/OaiyYZKQn2W05zC5mpPvGCgJo5pQWNQJpyovj9vW2xEX6+2HzNNzaqJFKrdlZrKP8kFrsTaap5L9we1jtT8iZQHKLu8pmyqdTPFykgfotW/eDxJxiSZuPBF231jXjn+TZaSNwHlCmyZFzpWv6SlDFuTIEj/2/YiifBHJmymU=
